import Head from "next/head";
import Image from "next/image";

import styles from "@/styles/Home.module.css";
import classes from "../styles/Home.module.css";
import Title from "@/components/Title/Title";
import SliderCategory from "@/components/SliderCategory/SliderCategory";
import store from "@/store/store";
import { observer } from "mobx-react-lite";
import axiosConfig from "@/utils/axiosConfig";
import axios from "axios";
import { useEffect } from "react";
import ThemeList from "@/components/ThemesList/ThemeList";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin", "cyrillic"] });

export const getStaticProps = async () => {
  const response = await axiosConfig().get(`categories/`);
  const categories = response.data.categories;

  const response2 = await axiosConfig().get(`themes/populars/`);
  const popularThemes = response2.data.themes;

  const response3 = await axiosConfig().get(`themes/?page=1&per_page=8`);
  const themeList = response3.data;

  return {
    props: { categories, popularThemes, themeList },
    revalidate: 60,
  };
};

const Home = observer(({ categories, popularThemes, themeList }) => {
  console.log(popularThemes, categories);
  useEffect(() => {
    store.categories.categorylist = categories !== undefined && categories;
    store.categories.PickedCategory = "";
    store.categories.popularThemes = popularThemes;
    store.categories.Themeslist = themeList.themes;
    const pages = themeList.page_data.split(",");
    store.pagination.countPages = pages.length;
    console.log(pages, pages.length);
    store.pagination.pageData = "main";
  }, []);

  return (
    <>
      <Head>
        <title>FunArt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={inter.style} className={classes.wrapper}>
        <Title
          title={"Coloring for fun ааавыыф   🌈"}
          description={"About 6k coloring pages"}
        />
        <SliderCategory categories={popularThemes}></SliderCategory>
        <ThemeList name={"All Colorings"} list={themeList.themes} />
      </div>
    </>
  );
});
export default Home;
